version: '3.9'

services:
  redis:
    image: redis:6.0.9-alpine3.12

  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data-volume:/var/lib/postgresql/data

  guard:
    build:
      context: .
      target: dev
    depends_on:
      - postgres
      - redis
      - chrome
    command: bundle exec guard --no-bundler-warning --no-interactions
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
      - log-volume:/app/log
      - node-modules-volume:/app/node_modules
      - tmp-volume:/app/tmp

  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '5901:5900'
    environment:
      - VNC_NO_PASSWORD=1
    extra_hosts:
      # Needed for linux hosts.
      - 'host.docker.internal:host-gateway'

volumes:
  bundle-volume: {}
  db-data-volume: {}
  log-volume: {}
  node-modules-volume: {}
  tmp-volume: {}
