version: '3.9'
services:
  redis:
    image: redis:6.0.9-alpine3.12
    ports:
      - '6379:6379'

  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db-data-volume: {}
